import React, { useState } from 'react';
import { MessageCircle, Send, Trash2 } from 'lucide-react';
import type { RecordComment } from '../../types';

export const CommentSection: React.FC<{ comments: RecordComment[]; onAdd: (text: string, author: string) => void; onRemove: (id: string) => void }> = ({ comments, onAdd, onRemove }) => {
  const [open, setOpen] = useState(false); const [text, setText] = useState(''); const [author, setAuthor] = useState(() => localStorage.getItem('cot-comment-author') || '');
  const submit = () => { if (!text.trim()) return; localStorage.setItem('cot-comment-author', author.trim() || '访客'); onAdd(text, author); setText(''); };
  return <section className="mt-4 border-t border-slate-200/60 pt-3 dark:border-slate-800/70"><button onClick={() => setOpen(!open)} className="flex min-h-10 items-center gap-1.5 text-xs text-slate-500 hover:text-sky-600 dark:text-slate-400 dark:hover:text-sky-400"><MessageCircle className="h-4 w-4" /> 评论 {comments.length ? '(' + comments.length + ')' : ''}</button>{open && <div className="mt-2 space-y-3 rounded-sm bg-slate-50/80 p-3 dark:bg-slate-900/50"><div className="space-y-2">{comments.map((comment) => <div key={comment.id} className="text-sm"><span className="font-medium text-sky-700 dark:text-sky-300">{comment.author}</span><span className="mx-1 text-slate-400">:</span><span className="text-slate-700 dark:text-slate-200">{comment.content}</span>{comment.local && <button onClick={() => onRemove(comment.id)} className="ml-2 text-slate-400 hover:text-red-500" aria-label="删除评论"><Trash2 className="inline h-3.5 w-3.5" /></button>}</div>)}</div><div className="space-y-2"><input value={author} onChange={(event) => setAuthor(event.target.value)} placeholder="昵称（可选）" className="h-9 w-full rounded-sm border border-slate-200 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:placeholder:text-slate-500" /><div className="flex gap-2"><textarea value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder="发表评论，Enter 发送" rows={2} className="min-h-9 flex-1 resize-y rounded-sm border border-slate-200 bg-white px-2 py-1.5 text-sm dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:placeholder:text-slate-500" /><button onClick={submit} className="self-end rounded-sm bg-sky-600 p-2 text-white hover:bg-sky-700 transition-colors" aria-label="发送评论"><Send className="h-4 w-4" /></button></div></div></div>}</section>;
};
